# Hardware configuration for Andromeda
# This file should be generated by nixos-generate-config
# Run: nixos-generate-config --show-hardware-config > hardware-configuration.nix
# Then replace this file with the generated output

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot / Kernel
  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ]; # Use kvm-amd for AMD CPUs
    extraModulePackages = [ ];
  };

  # Filesystems
  # Adjust these to match your actual disk layout
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # Media storage mount (adjust device path as needed)
  # fileSystems."/srv/media" = {
  #   device = "/dev/disk/by-label/media";
  #   fsType = "ext4";
  #   options = [ "nofail" ];
  # };

  swapDevices = [
    # { device = "/dev/disk/by-label/swap"; }
  ];

  # Networking (detected interfaces)
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable firmware updates
  hardware.enableRedistributableFirmware = true;
}
